version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build-V2]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-V2

  build-backend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build-V2]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build-V2

  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build-V2]
      - run:
          name: frontend-test
          command: |
            cd frontend
            npm run test

  test-backend:
    executor: node-executor
    steps:
      - checkout 
      - restore_cache:
          keys: [backend-build-V2]
      - run:
          name: backend-test
          command: |
            cd backend
            npm run test

  scan-frontend:
    executor: node-executor
    steps:
      - checkout 
      - restore_cache:
          keys: [frontend-build-V2]
      - run:
          name: scan-frontend
          command: |
            cd frontend
            npm audit --audit-level=critical
              
  scan-backend:
    executor: node-executor
    steps:
      - checkout 
      - restore_cache:
          keys: [backend-build-V2]
      - run:
          name: scan-backend
          command: |
            cd backend
            npm audit --audit-level=critical

###
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [test-backend]
      - scan-frontend:
          requires: [test-frontend]