version: 2.1
          
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm start
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm login
            npm install
            npm run start:dev
            npm run webpack
            npm run start:hmr
            npm run start:prod
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

###
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
